FROM scratch

# 地图数据需要手动复制到构建上下文
# 构建前将 maps/ vmaps/ mmaps/ dbc/ cameras/ 放到当前目录

COPY maps/ /data/maps/
COPY vmaps/ /data/vmaps/
COPY mmaps/ /data/mmaps/
COPY dbc/ /data/dbc/
COPY cameras/ /data/cameras/
